[project]
name = "trace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "ipykernel>=7.1.0",
    "trl[judges]>=0.26.2",
]
